"""remove name unique

Revision ID: 173191f8e501
Revises: 7392bdbf73d6
Create Date: 2023-12-09 17:17:01.150360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173191f8e501'
down_revision: Union[str, None] = '7392bdbf73d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    # ### end Alembic commands ###
